language: node_js

node_js:
  - "8.11.3"

install: 
  - yarn

script: 
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  repo: https://github.com/guoshencheng/guoshencheng.github.io.git
  keep-history: true
  local_dir: public
  name: $GIT_NAME
  email: $GIT_EMAIL
  on:
    branch: master
